title: Space Monkey
email: spacemonkey@evil.nastyvirus.download
description: > # this means to ignore newlines until "baseurl:"
twitter: <a href="https://twitter.com/sp4c3m0nk3">@sp4c3m0nk3y</a><br/><img src="img/sm-twitter-logo.jpg">
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: ""
theme: jekyll-theme-minimal
