title: Space Monkey
email: spacemonkey@evil.nastyvirus.download
description: > # this means to ignore newlines until "baseurl:"
  twitter: <a href="https://twitter.com/sp4c3m0nk3y/">@sp4c3m0nk3y</a><br/><img src="http://evil.nastyvirus.download/img/red-yellow-trans-logo.png">
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme
theme: jekyll-theme-minimal
